version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ace-backend
    ports:
      - "7000:8000"  # host:container
    volumes:
      - ./backend:/app  # live reload during dev (optional)
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      UV_SYSTEM_PYTHON: 1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ace-frontend
    ports:
      - "6000:3000"  # host:container
    volumes:
      - ./frontend:/app
      - /app/node_modules  # live reload during dev (optional)
    restart: unless-stopped
